before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - '-s -w -X "main.godlVersion={{.Tag}}" -X "main.buildDate={{.Date}}" -X "main.goVersion={{.Env.GO_VERSION}}" -X "main.gitHash={{.ShortCommit}}"'
    main: ./cmd/main.go
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
