before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - '-s -w -X "main.gitTag={{.Tag}}" -X "main.buildTime={{.Date}}"'
    main: ./cmd/godl
checksum:
  name_template: '{{ .ProjectName }}_{{.Tag}}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
