language: go
go:
- 1.12.x
- master
os:
- linux
- osx
osx_image: xcode10.1
dist: trusty
env:
  - GO111MODULE=on
before_install:
  - go get github.com/mattn/goveralls
install: true
script:
  - make fetch
  - goveralls -service=travis-ci
  - make build
