language: go
go:
- 1.16.x
os:
- osx
osx_image: xcode12.2
before_install:
- go get github.com/mattn/goveralls
- curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
  | sh -s -- -b $(go env GOPATH)/bin v1.38.0
- golangci-lint --version
- curl -sfL https://git.io/goreleaser | sh -s -- check
install: true
script:
- make fetch
- make lint
- make test-cover
- goveralls -coverprofile=cover.out -service=travis-ci
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
env:
  global:
  - secure: dZeeEcfH+jx/8bM4MPwhF2NVpEgGNl3P+9CnnPfMFIPiWw3TnITaknlfFF2+lWQM/5WD2Ic8Q3bBLRXtncikCoWwnWyKLCiIbfll4SHSXrpb2O6fknblbLmRJFtwec8CAlIVpem3IPdU10iCYPFuCMqnHZt36SDlZA3hrIsFn8a7eBlraoOIkJDh9QF9htQuI4XyS6URyG1tWtgXrHMsWfqVszxlY5GmECCRCsRa7ArTFy8HySzu0lCMqiK6GjUbcs4RsTecEstCOqqMIfJLHlGovIh/AkAKjwwf7xL8sm/aREWUZfSWeyRsrTrDHYl7bgZTy2XQanHwsJrTcfnsxWZhjDmDCjcq//tZcBoVrD50N++KBjr4BzQh7g2YbDjwDoplZ3kE+Eu+f04/6UXaLiQDBMGQ7O4f8K/A2uTQ8PYxACtRWgdhnv+8Pl91fTi9ugeTEVing0nQIMpMjc4RcRJY02/LNpWKZmXbU1RhAauJixS9UuZA5VJ8u7CS8lqKmoboKIuRm4Cjqbw5nQNUsprHf+t4uqMduJmW7p6DbAim1FLjR6DghC1qmPThu9mOFtKYsbB9eon7mRWFNngkrGQ3cNyEtAC0vtJCYh4Q20l4mtLsXmK5YXYvTI74/o5iqNp/Tn4LY1yfyhkUdP+g0YWk7W3vQZEZYZqP0gEoLfM=
  - secure: tbYYGh9kcwG0aifoos8GKMobw3sjht1TdSubVM7W+emmmwIQ19aO1poTJa4h0PV43ExuwRbQoaWgYW4qoe5S/MRuJszT+04SPnvH1/DjZAdNnujxb2yF0yYWoEtuP5HkCdAhLZZls1H/bxCbrBJCzPR0jXHYJf3hnM06LbsCYTjKd7QtmvnQ+Ce5KpTZQtZrwimPIE/n0NUDohiacqKwD2PDUuB6OUMYBQGWMtwVcPed24o0fdfVuPfB5BT2hwPfFPAB+hIQsNBWIpRM2na9WZJ4IX3q4y0HQ2yfeY5xqlzhnKrAz83+bxDoks7v6vwbAK//7MjRBobia7c+uWDFMUHvjV5pMARLm0xwb+h7CrzYRYehGw6p+YXAoGIH9NBx4ib8b1c6kcom2SxLNYt6h/LhZ9hGJUdreniwC/MvC2XtTRQwrB8D7zLt4R1f6HAQpvrZhbUGbVOO+QEwmYSHrk7v5gIt7kOx2lvLJk3krMfrz+d/JybsSviM2AiCDciyrimQNqT0iEKw+qvWcleIV8hDWUF5dMRJOKNJZUJXVcmg+b1v2hBnIiGAv9bN3sxWfVZs/dHYTBDMR/iqudjaAvuYAVlG/L/rA7ubx/pzetn3GQa77wxhNUtGJwNOMe5M+M630bhGM/zEILTYv1rfE2cq2dvxFFMl0Kvc34f65Js=
