name: CI/CD

on:
  [push]

jobs:
  test:
    name: Test with Coverage
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Run tests
        run: make test/cover
      - name: Send coverage to Coveralls
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make coveralls

  golangci:
    name: Linting
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          args: --timeout 3m --verbose

  goreleaser:
    name: Make Release
    needs: [golangci, test]
    runs-on: macos-11
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Set GO_VERSION
        run: echo "GO_VERSION=$(go env GOVERSION)" >> $GITHUB_ENV
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GO_VERSION: ${{ env.GO_VERSION }}
